
services:
  php-fpm:
    build:
      context: ./woofwalks_back
      dockerfile: Dockerfile.php-fpm.dev
    container_name: woofwalks_php-fpm
    volumes:
      - ./logs:/var/www/html/var/log
      - ./woofwalks_back:/var/www/html
    networks:
      - woofwalks-network
    expose:
      - 9000
    environment:
      - APP_ENV=dev
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: woofwalks_nginx
    ports:
      - "8000:80"
      - "8443:443" 
    volumes:
      - ./woofwalks_back:/var/www/html
      - ./woofwalks_back/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro 
    networks:
      - woofwalks-network
    depends_on:
      - php-fpm

  frontend:
    build:
      context: ./woofwalks_front
      dockerfile: Dockerfile.dev
    container_name: woofwalks_front
    volumes:
      - ./woofwalks_front:/app
      - ./woofwalks_front/certs:/app/certs
    ports:
      - "3000:3000"
    networks:
      - woofwalks-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=https://localhost:8443 
      - HTTPS=true 
      - SSL_CRT_FILE=/app/certs/frontend_cert.crt
      - SSL_KEY_FILE=/app/certs/frontend_key.key
    stdin_open: true
    tty: true
    # depends_on:
    #   - nginx

  db:
    image: mysql:5.7
    container_name: woofwalks_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      - woofwalks-network
    volumes:
      - ./docker/mysql-init:/docker-entrypoint-initdb.d 
      - mysql_data:/var/lib/mysql
      
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p$${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"]      
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: woofwalks_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - woofwalks-network
    depends_on:
      - db

networks:
  woofwalks-network:
    driver: bridge

volumes:

  mysql_data:
    driver: local
  symfony_cache:
  symfony_log:
  composer_cache:
