# version: "3.8"

# services:
#   # Service pour le backend (API Platform)
#   backend:
#     build:
#       context: ./woofwalks_back
#     container_name: woofwalks_back
#     ports:
#       - "8000:8000" # Exposer le port 8000
#     volumes:
#       - ./woofwalks_back:/var/www/html
#     networks:
#       - woofwalks-network
#     environment:
#       - APP_ENV=dev

#   # Service pour le frontend (React)
#   frontend:
#     build:
#       context: ./woofwalks_front
#     container_name: woofwalks_front
#     volumes:
#       - ./src:/var/www/html/src # Synchronisation entre le code source local et le conteneur
#     ports:
#       - "3000:80" # Exposer le port 3000 sur le conteneur
#     networks:
#       - woofwalks-network
#     environment:
#       - REACT_APP_API_URL=http://woofwalks_back:8000 # URL de l'API backend dans le réseau Docker

#   db:
#     image: mysql:5.7
#     container_name: woofwalks_db
#     environment:
#       MYSQL_ROOT_PASSWORD: Poison8926!
#       MYSQL_DATABASE: woofwalks
#     ports:
#       - "3306:3306"
#     networks:
#       - woofwalks-network
#     volumes:
#       - mysql_data:/var/lib/mysql

# networks:
#   woofwalks-network:
#     driver: bridge

# volumes:
#   mysql_data:
#     driver: local

# version: "3.8"
version: "3.8"
services:
  php-fpm:
    build:
      context: ./woofwalks_back
      dockerfile: Dockerfile.php-fpm
    container_name: woofwalks_php-fpm
    volumes:
      - ./woofwalks_back:/var/www/html:delegated
      - ./woofwalks_back/public/media:/var/www/html/public/media:delegated
      - symfony_cache:/var/www/html/var/cache
      - symfony_log:/var/www/html/var/log
      - composer_cache:/var/www/html/.composer/cache
    networks:
      - woofwalks-network
    expose:
      - 9000
    environment:
      - APP_ENV=dev
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: woofwalks_nginx
    ports:
      - "8000:80"
    volumes:
      - ./woofwalks_back:/var/www/html:ro
      - ./woofwalks_back/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - woofwalks-network
    depends_on:
      - php-fpm

  frontend:
    build:
      context: ./woofwalks_front
    container_name: woofwalks_front
    volumes:
      - ./woofwalks_front:/app
    ports:
      - "3000:3000"
    networks:
      - woofwalks-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://woofwalks_nginx:8000
    stdin_open: true
    tty: true
    depends_on:
      - nginx

  db:
    image: mysql:5.7
    container_name: woofwalks_db
    environment:
      MYSQL_ROOT_PASSWORD: Poison8926!
      MYSQL_DATABASE: woofwalks
    ports:
      - "3306:3306"
    networks:
      - woofwalks-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-pPoison8926!", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: woofwalks_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Poison8926!
    networks:
      - woofwalks-network
    depends_on:
      - db

networks:
  woofwalks-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  symfony_cache:
  symfony_log:
  composer_cache:
