env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
<<<<<<< HEAD
    - https://localhost:8443
=======
    - https://woofwalks_nginx:443
>>>>>>> develop
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
<<<<<<< HEAD
    url: https://localhost:8443
=======
    url: https://woofwalks_nginx:443
>>>>>>> develop
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: /zap/wrk/rapport.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
