nelmio_security:
  #Désactivation pour le dev
  csp:
    enabled: false 
    # ajoute l'en-tête X-Content-Type-Options: nosniff, ce qui force le navigateur à respecter le type de contenu déclaré : .txt = .txt - jamais exécuté comme du JS
  clickjacking:
    paths:
      '^/': { header: DENY }
  content_type:
    nosniff: true
    #Forçage du HTTPS
  forced_ssl:
    hosts: ['localhost']
    hsts_max_age: 31536000
    hsts_subdomains: true
    hsts_preload: true
