
security:
    #Algorithme auto de symfony pour le hashage
    password_hashers:
        App\Entity\User: 'auto'
    #Classe User comme source de donnée des Utilisateurs (auth par mail)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    #Déf générale de comment sont sécurisée les diff parties de l'appli
    firewalls:
        #Fichiers qui restent accessible pendant le dev- sans etre authentifié
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #Route de login : login_check en utilisant les paramétrages de app_user_provider
        login:
            pattern: ^/api/login_check$
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Toutes les routes api sécurisées par custom_authenticatos (CookieTokenAuthenticator)
        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
              - App\Security\CookieTokenAuthenticator
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            logout:
                path: /api/logout
        refresh_token:
            pattern: ^/api/token/refresh$
            stateless: true
            # Pas de custom_authenticator ici si tu gères via controller manuellement
            # anonymous: true
        #Route de rafraichissement du refresh_jwt
        # refresh:
        #     pattern: ^/api/token/refresh$
        #     stateless: true
        #     custom_authenticators:
        #         - App\Security\CookieTokenAuthenticator
        #     provider: app_user_provider

        # refresh_jwt:
        #     pattern: ^/api/token/refresh$
        #     stateless: true
        #     refresh_jwt: ~
        #     provider: app_user_provider
        #     user_checker: App\Security\UserChecker
        #Permet l'acces à la doc de l'api -- false 
        api_doc:
            pattern: ^/api/(docs|contexts)
            security: false
    # Déclaration des path et droits associés
    access_control:
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api/confirm-email/, roles: PUBLIC_ACCESS }
        - { path: ^/api/users$, methods: [POST], roles: PUBLIC_ACCESS }
        - { path: ^/api/me, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/walks/?$, roles: PUBLIC_ACCESS }
        - { path: ^/api/parks/?$, roles: PUBLIC_ACCESS }
        - { path: ^/api/(docs|contexts), roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
