# server {
#     listen 80;
#     server_name localhost;
#     root /var/www/html/public;
#     index index.php index.html;

#     location / {
#         try_files $uri $uri/ /index.php?$query_string;
#     }

#     location ~ \.php$ {
#         # Utilisez le nom du service php-fpm et le port exposé
#         fastcgi_pass php-fpm:9000;
#         fastcgi_index index.php;
#         include fastcgi_params;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#     }

#     location ~ /\.ht {
#         deny all;
#     }
# }

# woofwalks_back/docker/nginx/default.conf
server {
    listen 80;
    listen 443 ssl; # Écoute sur le port HTTPS
    server_name localhost;
    root /var/www/html/public;

    # Redirige HTTP vers HTTPS
    if ($scheme = http) {
        return 301 https://$host$request_uri;
    }

    # Configuration SSL
    ssl_certificate /etc/nginx/certs/nginx.crt; # Chemin vers ton certificat dans le conteneur
    ssl_certificate_key /etc/nginx/certs/nginx.key; # Chemin vers ta clé dans le conteneur
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        # try to serve file directly, fallback to index.php
        try_files $uri /index.php$is_args$query_string;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass woofwalks_php-fpm:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}