server {
    listen 80;
    server_name localhost;

    # Frontend React
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Backend Symfony
    location /api {
        root /var/www/html/public;
        try_files $uri /index.php$is_args$query_string;
    }

    location ~ ^/index\.php(/|$) {
        # Socket PHP-FPM interne
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
        internal;
    }

    # Média Symfony
    location /media/ {
        alias /var/www/html/public/media/;
        access_log off;
        expires 30d;
    }

    # Sécurité
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
}