name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: # <-- Placez les variables d'environnement ici
      APP_ENV: test
      DATABASE_URL: 'mysql://root:@127.0.0.1:3306/woofwalks_test'
      
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: woofwalks_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: 'pdo_mysql, mbstring'
          tools: composer
      
      - name: Create .env file for CI
        run: |
          echo 'APP_SECRET=a_secure_secret' > .env
          echo 'APP_ENV=test' >> .env
        working-directory: woofwalks_back

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist
        working-directory: woofwalks_back

      - name: Prepare Test Database
        run: chmod +x bin/console
        working-directory: woofwalks_back

      - name: Prepare test Database
          bin/console doctrine:database:create
          bin/console doctrine:migrations:migrate --no-interaction
          bin/console doctrine:fixtures:load --no-interaction
        working-directory: woofwalks_back

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit
        working-directory: woofwalks_back